/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.red.search.dejavu.recall.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class SearchResult implements org.apache.thrift.TBase<SearchResult, SearchResult._Fields>, java.io.Serializable, Cloneable, Comparable<SearchResult> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("SearchResult");

  private static final org.apache.thrift.protocol.TField RES_FIELD_DESC = new org.apache.thrift.protocol.TField("res", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField DOCS_FIELD_DESC = new org.apache.thrift.protocol.TField("docs", org.apache.thrift.protocol.TType.LIST, (short)2);
  private static final org.apache.thrift.protocol.TField ERROR_INFO_FIELD_DESC = new org.apache.thrift.protocol.TField("error_info", org.apache.thrift.protocol.TType.STRING, (short)3);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new SearchResultStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new SearchResultTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable com.xiaohongshu.infra.rpc.base.Result res; // required
  public @org.apache.thrift.annotation.Nullable java.util.List<SearchResultDoc> docs; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String error_info; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    RES((short)1, "res"),
    DOCS((short)2, "docs"),
    ERROR_INFO((short)3, "error_info");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // RES
          return RES;
        case 2: // DOCS
          return DOCS;
        case 3: // ERROR_INFO
          return ERROR_INFO;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.RES, new org.apache.thrift.meta_data.FieldMetaData("res", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, com.xiaohongshu.infra.rpc.base.Result.class)));
    tmpMap.put(_Fields.DOCS, new org.apache.thrift.meta_data.FieldMetaData("docs", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, SearchResultDoc.class))));
    tmpMap.put(_Fields.ERROR_INFO, new org.apache.thrift.meta_data.FieldMetaData("error_info", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(SearchResult.class, metaDataMap);
  }

  public SearchResult() {
  }

  public SearchResult(
    com.xiaohongshu.infra.rpc.base.Result res,
    java.util.List<SearchResultDoc> docs,
    java.lang.String error_info)
  {
    this();
    this.res = res;
    this.docs = docs;
    this.error_info = error_info;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public SearchResult(SearchResult other) {
    if (other.isSetRes()) {
      this.res = new com.xiaohongshu.infra.rpc.base.Result(other.res);
    }
    if (other.isSetDocs()) {
      java.util.List<SearchResultDoc> __this__docs = new java.util.ArrayList<SearchResultDoc>(other.docs.size());
      for (SearchResultDoc other_element : other.docs) {
        __this__docs.add(new SearchResultDoc(other_element));
      }
      this.docs = __this__docs;
    }
    if (other.isSetError_info()) {
      this.error_info = other.error_info;
    }
  }

  public SearchResult deepCopy() {
    return new SearchResult(this);
  }

  @Override
  public void clear() {
    this.res = null;
    this.docs = null;
    this.error_info = null;
  }

  @org.apache.thrift.annotation.Nullable
  public com.xiaohongshu.infra.rpc.base.Result getRes() {
    return this.res;
  }

  public SearchResult setRes(@org.apache.thrift.annotation.Nullable com.xiaohongshu.infra.rpc.base.Result res) {
    this.res = res;
    return this;
  }

  public void unsetRes() {
    this.res = null;
  }

  /** Returns true if field res is set (has been assigned a value) and false otherwise */
  public boolean isSetRes() {
    return this.res != null;
  }

  public void setResIsSet(boolean value) {
    if (!value) {
      this.res = null;
    }
  }

  public int getDocsSize() {
    return (this.docs == null) ? 0 : this.docs.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<SearchResultDoc> getDocsIterator() {
    return (this.docs == null) ? null : this.docs.iterator();
  }

  public void addToDocs(SearchResultDoc elem) {
    if (this.docs == null) {
      this.docs = new java.util.ArrayList<SearchResultDoc>();
    }
    this.docs.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<SearchResultDoc> getDocs() {
    return this.docs;
  }

  public SearchResult setDocs(@org.apache.thrift.annotation.Nullable java.util.List<SearchResultDoc> docs) {
    this.docs = docs;
    return this;
  }

  public void unsetDocs() {
    this.docs = null;
  }

  /** Returns true if field docs is set (has been assigned a value) and false otherwise */
  public boolean isSetDocs() {
    return this.docs != null;
  }

  public void setDocsIsSet(boolean value) {
    if (!value) {
      this.docs = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getError_info() {
    return this.error_info;
  }

  public SearchResult setError_info(@org.apache.thrift.annotation.Nullable java.lang.String error_info) {
    this.error_info = error_info;
    return this;
  }

  public void unsetError_info() {
    this.error_info = null;
  }

  /** Returns true if field error_info is set (has been assigned a value) and false otherwise */
  public boolean isSetError_info() {
    return this.error_info != null;
  }

  public void setError_infoIsSet(boolean value) {
    if (!value) {
      this.error_info = null;
    }
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case RES:
      if (value == null) {
        unsetRes();
      } else {
        setRes((com.xiaohongshu.infra.rpc.base.Result)value);
      }
      break;

    case DOCS:
      if (value == null) {
        unsetDocs();
      } else {
        setDocs((java.util.List<SearchResultDoc>)value);
      }
      break;

    case ERROR_INFO:
      if (value == null) {
        unsetError_info();
      } else {
        setError_info((java.lang.String)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case RES:
      return getRes();

    case DOCS:
      return getDocs();

    case ERROR_INFO:
      return getError_info();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case RES:
      return isSetRes();
    case DOCS:
      return isSetDocs();
    case ERROR_INFO:
      return isSetError_info();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof SearchResult)
      return this.equals((SearchResult)that);
    return false;
  }

  public boolean equals(SearchResult that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_res = true && this.isSetRes();
    boolean that_present_res = true && that.isSetRes();
    if (this_present_res || that_present_res) {
      if (!(this_present_res && that_present_res))
        return false;
      if (!this.res.equals(that.res))
        return false;
    }

    boolean this_present_docs = true && this.isSetDocs();
    boolean that_present_docs = true && that.isSetDocs();
    if (this_present_docs || that_present_docs) {
      if (!(this_present_docs && that_present_docs))
        return false;
      if (!this.docs.equals(that.docs))
        return false;
    }

    boolean this_present_error_info = true && this.isSetError_info();
    boolean that_present_error_info = true && that.isSetError_info();
    if (this_present_error_info || that_present_error_info) {
      if (!(this_present_error_info && that_present_error_info))
        return false;
      if (!this.error_info.equals(that.error_info))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetRes()) ? 131071 : 524287);
    if (isSetRes())
      hashCode = hashCode * 8191 + res.hashCode();

    hashCode = hashCode * 8191 + ((isSetDocs()) ? 131071 : 524287);
    if (isSetDocs())
      hashCode = hashCode * 8191 + docs.hashCode();

    hashCode = hashCode * 8191 + ((isSetError_info()) ? 131071 : 524287);
    if (isSetError_info())
      hashCode = hashCode * 8191 + error_info.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(SearchResult other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetRes()).compareTo(other.isSetRes());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRes()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.res, other.res);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetDocs()).compareTo(other.isSetDocs());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDocs()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.docs, other.docs);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetError_info()).compareTo(other.isSetError_info());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetError_info()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.error_info, other.error_info);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("SearchResult(");
    boolean first = true;

    sb.append("res:");
    if (this.res == null) {
      sb.append("null");
    } else {
      sb.append(this.res);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("docs:");
    if (this.docs == null) {
      sb.append("null");
    } else {
      sb.append(this.docs);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("error_info:");
    if (this.error_info == null) {
      sb.append("null");
    } else {
      sb.append(this.error_info);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (res != null) {
      res.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class SearchResultStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public SearchResultStandardScheme getScheme() {
      return new SearchResultStandardScheme();
    }
  }

  private static class SearchResultStandardScheme extends org.apache.thrift.scheme.StandardScheme<SearchResult> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, SearchResult struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // RES
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.res = new com.xiaohongshu.infra.rpc.base.Result();
              struct.res.read(iprot);
              struct.setResIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // DOCS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                struct.docs = new java.util.ArrayList<SearchResultDoc>(_list0.size);
                @org.apache.thrift.annotation.Nullable SearchResultDoc _elem1;
                for (int _i2 = 0; _i2 < _list0.size; ++_i2)
                {
                  _elem1 = new SearchResultDoc();
                  _elem1.read(iprot);
                  struct.docs.add(_elem1);
                }
                iprot.readListEnd();
              }
              struct.setDocsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // ERROR_INFO
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.error_info = iprot.readString();
              struct.setError_infoIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, SearchResult struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.res != null) {
        oprot.writeFieldBegin(RES_FIELD_DESC);
        struct.res.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.docs != null) {
        oprot.writeFieldBegin(DOCS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.docs.size()));
          for (SearchResultDoc _iter3 : struct.docs)
          {
            _iter3.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.error_info != null) {
        oprot.writeFieldBegin(ERROR_INFO_FIELD_DESC);
        oprot.writeString(struct.error_info);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class SearchResultTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public SearchResultTupleScheme getScheme() {
      return new SearchResultTupleScheme();
    }
  }

  private static class SearchResultTupleScheme extends org.apache.thrift.scheme.TupleScheme<SearchResult> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, SearchResult struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetRes()) {
        optionals.set(0);
      }
      if (struct.isSetDocs()) {
        optionals.set(1);
      }
      if (struct.isSetError_info()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetRes()) {
        struct.res.write(oprot);
      }
      if (struct.isSetDocs()) {
        {
          oprot.writeI32(struct.docs.size());
          for (SearchResultDoc _iter4 : struct.docs)
          {
            _iter4.write(oprot);
          }
        }
      }
      if (struct.isSetError_info()) {
        oprot.writeString(struct.error_info);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, SearchResult struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.res = new com.xiaohongshu.infra.rpc.base.Result();
        struct.res.read(iprot);
        struct.setResIsSet(true);
      }
      if (incoming.get(1)) {
        {
          org.apache.thrift.protocol.TList _list5 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.docs = new java.util.ArrayList<SearchResultDoc>(_list5.size);
          @org.apache.thrift.annotation.Nullable SearchResultDoc _elem6;
          for (int _i7 = 0; _i7 < _list5.size; ++_i7)
          {
            _elem6 = new SearchResultDoc();
            _elem6.read(iprot);
            struct.docs.add(_elem6);
          }
        }
        struct.setDocsIsSet(true);
      }
      if (incoming.get(2)) {
        struct.error_info = iprot.readString();
        struct.setError_infoIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

