/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.red.search.dejavu.relevance.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class GBDTResponse implements org.apache.thrift.TBase<GBDTResponse, GBDTResponse._Fields>, java.io.Serializable, Cloneable, Comparable<GBDTResponse> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("GBDTResponse");

  private static final org.apache.thrift.protocol.TField RES_FIELD_DESC = new org.apache.thrift.protocol.TField("res", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField SCORES_FIELD_DESC = new org.apache.thrift.protocol.TField("scores", org.apache.thrift.protocol.TType.LIST, (short)2);
  private static final org.apache.thrift.protocol.TField FEATURE_SCORES_FIELD_DESC = new org.apache.thrift.protocol.TField("feature_scores", org.apache.thrift.protocol.TType.LIST, (short)3);
  private static final org.apache.thrift.protocol.TField ERROR_INFO_FIELD_DESC = new org.apache.thrift.protocol.TField("error_info", org.apache.thrift.protocol.TType.STRING, (short)4);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new GBDTResponseStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new GBDTResponseTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable com.xiaohongshu.infra.rpc.base.Result res; // required
  public @org.apache.thrift.annotation.Nullable java.util.List<RelevanceScore> scores; // required
  public @org.apache.thrift.annotation.Nullable java.util.List<java.lang.Double> feature_scores; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String error_info; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    RES((short)1, "res"),
    SCORES((short)2, "scores"),
    FEATURE_SCORES((short)3, "feature_scores"),
    ERROR_INFO((short)4, "error_info");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // RES
          return RES;
        case 2: // SCORES
          return SCORES;
        case 3: // FEATURE_SCORES
          return FEATURE_SCORES;
        case 4: // ERROR_INFO
          return ERROR_INFO;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.RES, new org.apache.thrift.meta_data.FieldMetaData("res", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, com.xiaohongshu.infra.rpc.base.Result.class)));
    tmpMap.put(_Fields.SCORES, new org.apache.thrift.meta_data.FieldMetaData("scores", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, RelevanceScore.class))));
    tmpMap.put(_Fields.FEATURE_SCORES, new org.apache.thrift.meta_data.FieldMetaData("feature_scores", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE))));
    tmpMap.put(_Fields.ERROR_INFO, new org.apache.thrift.meta_data.FieldMetaData("error_info", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(GBDTResponse.class, metaDataMap);
  }

  public GBDTResponse() {
  }

  public GBDTResponse(
    com.xiaohongshu.infra.rpc.base.Result res,
    java.util.List<RelevanceScore> scores,
    java.util.List<java.lang.Double> feature_scores,
    java.lang.String error_info)
  {
    this();
    this.res = res;
    this.scores = scores;
    this.feature_scores = feature_scores;
    this.error_info = error_info;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public GBDTResponse(GBDTResponse other) {
    if (other.isSetRes()) {
      this.res = new com.xiaohongshu.infra.rpc.base.Result(other.res);
    }
    if (other.isSetScores()) {
      java.util.List<RelevanceScore> __this__scores = new java.util.ArrayList<RelevanceScore>(other.scores.size());
      for (RelevanceScore other_element : other.scores) {
        __this__scores.add(new RelevanceScore(other_element));
      }
      this.scores = __this__scores;
    }
    if (other.isSetFeature_scores()) {
      java.util.List<java.lang.Double> __this__feature_scores = new java.util.ArrayList<java.lang.Double>(other.feature_scores);
      this.feature_scores = __this__feature_scores;
    }
    if (other.isSetError_info()) {
      this.error_info = other.error_info;
    }
  }

  public GBDTResponse deepCopy() {
    return new GBDTResponse(this);
  }

  @Override
  public void clear() {
    this.res = null;
    this.scores = null;
    this.feature_scores = null;
    this.error_info = null;
  }

  @org.apache.thrift.annotation.Nullable
  public com.xiaohongshu.infra.rpc.base.Result getRes() {
    return this.res;
  }

  public GBDTResponse setRes(@org.apache.thrift.annotation.Nullable com.xiaohongshu.infra.rpc.base.Result res) {
    this.res = res;
    return this;
  }

  public void unsetRes() {
    this.res = null;
  }

  /** Returns true if field res is set (has been assigned a value) and false otherwise */
  public boolean isSetRes() {
    return this.res != null;
  }

  public void setResIsSet(boolean value) {
    if (!value) {
      this.res = null;
    }
  }

  public int getScoresSize() {
    return (this.scores == null) ? 0 : this.scores.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<RelevanceScore> getScoresIterator() {
    return (this.scores == null) ? null : this.scores.iterator();
  }

  public void addToScores(RelevanceScore elem) {
    if (this.scores == null) {
      this.scores = new java.util.ArrayList<RelevanceScore>();
    }
    this.scores.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<RelevanceScore> getScores() {
    return this.scores;
  }

  public GBDTResponse setScores(@org.apache.thrift.annotation.Nullable java.util.List<RelevanceScore> scores) {
    this.scores = scores;
    return this;
  }

  public void unsetScores() {
    this.scores = null;
  }

  /** Returns true if field scores is set (has been assigned a value) and false otherwise */
  public boolean isSetScores() {
    return this.scores != null;
  }

  public void setScoresIsSet(boolean value) {
    if (!value) {
      this.scores = null;
    }
  }

  public int getFeature_scoresSize() {
    return (this.feature_scores == null) ? 0 : this.feature_scores.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<java.lang.Double> getFeature_scoresIterator() {
    return (this.feature_scores == null) ? null : this.feature_scores.iterator();
  }

  public void addToFeature_scores(double elem) {
    if (this.feature_scores == null) {
      this.feature_scores = new java.util.ArrayList<java.lang.Double>();
    }
    this.feature_scores.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<java.lang.Double> getFeature_scores() {
    return this.feature_scores;
  }

  public GBDTResponse setFeature_scores(@org.apache.thrift.annotation.Nullable java.util.List<java.lang.Double> feature_scores) {
    this.feature_scores = feature_scores;
    return this;
  }

  public void unsetFeature_scores() {
    this.feature_scores = null;
  }

  /** Returns true if field feature_scores is set (has been assigned a value) and false otherwise */
  public boolean isSetFeature_scores() {
    return this.feature_scores != null;
  }

  public void setFeature_scoresIsSet(boolean value) {
    if (!value) {
      this.feature_scores = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getError_info() {
    return this.error_info;
  }

  public GBDTResponse setError_info(@org.apache.thrift.annotation.Nullable java.lang.String error_info) {
    this.error_info = error_info;
    return this;
  }

  public void unsetError_info() {
    this.error_info = null;
  }

  /** Returns true if field error_info is set (has been assigned a value) and false otherwise */
  public boolean isSetError_info() {
    return this.error_info != null;
  }

  public void setError_infoIsSet(boolean value) {
    if (!value) {
      this.error_info = null;
    }
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case RES:
      if (value == null) {
        unsetRes();
      } else {
        setRes((com.xiaohongshu.infra.rpc.base.Result)value);
      }
      break;

    case SCORES:
      if (value == null) {
        unsetScores();
      } else {
        setScores((java.util.List<RelevanceScore>)value);
      }
      break;

    case FEATURE_SCORES:
      if (value == null) {
        unsetFeature_scores();
      } else {
        setFeature_scores((java.util.List<java.lang.Double>)value);
      }
      break;

    case ERROR_INFO:
      if (value == null) {
        unsetError_info();
      } else {
        setError_info((java.lang.String)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case RES:
      return getRes();

    case SCORES:
      return getScores();

    case FEATURE_SCORES:
      return getFeature_scores();

    case ERROR_INFO:
      return getError_info();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case RES:
      return isSetRes();
    case SCORES:
      return isSetScores();
    case FEATURE_SCORES:
      return isSetFeature_scores();
    case ERROR_INFO:
      return isSetError_info();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof GBDTResponse)
      return this.equals((GBDTResponse)that);
    return false;
  }

  public boolean equals(GBDTResponse that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_res = true && this.isSetRes();
    boolean that_present_res = true && that.isSetRes();
    if (this_present_res || that_present_res) {
      if (!(this_present_res && that_present_res))
        return false;
      if (!this.res.equals(that.res))
        return false;
    }

    boolean this_present_scores = true && this.isSetScores();
    boolean that_present_scores = true && that.isSetScores();
    if (this_present_scores || that_present_scores) {
      if (!(this_present_scores && that_present_scores))
        return false;
      if (!this.scores.equals(that.scores))
        return false;
    }

    boolean this_present_feature_scores = true && this.isSetFeature_scores();
    boolean that_present_feature_scores = true && that.isSetFeature_scores();
    if (this_present_feature_scores || that_present_feature_scores) {
      if (!(this_present_feature_scores && that_present_feature_scores))
        return false;
      if (!this.feature_scores.equals(that.feature_scores))
        return false;
    }

    boolean this_present_error_info = true && this.isSetError_info();
    boolean that_present_error_info = true && that.isSetError_info();
    if (this_present_error_info || that_present_error_info) {
      if (!(this_present_error_info && that_present_error_info))
        return false;
      if (!this.error_info.equals(that.error_info))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetRes()) ? 131071 : 524287);
    if (isSetRes())
      hashCode = hashCode * 8191 + res.hashCode();

    hashCode = hashCode * 8191 + ((isSetScores()) ? 131071 : 524287);
    if (isSetScores())
      hashCode = hashCode * 8191 + scores.hashCode();

    hashCode = hashCode * 8191 + ((isSetFeature_scores()) ? 131071 : 524287);
    if (isSetFeature_scores())
      hashCode = hashCode * 8191 + feature_scores.hashCode();

    hashCode = hashCode * 8191 + ((isSetError_info()) ? 131071 : 524287);
    if (isSetError_info())
      hashCode = hashCode * 8191 + error_info.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(GBDTResponse other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetRes()).compareTo(other.isSetRes());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRes()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.res, other.res);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetScores()).compareTo(other.isSetScores());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetScores()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.scores, other.scores);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetFeature_scores()).compareTo(other.isSetFeature_scores());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFeature_scores()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.feature_scores, other.feature_scores);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetError_info()).compareTo(other.isSetError_info());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetError_info()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.error_info, other.error_info);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("GBDTResponse(");
    boolean first = true;

    sb.append("res:");
    if (this.res == null) {
      sb.append("null");
    } else {
      sb.append(this.res);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("scores:");
    if (this.scores == null) {
      sb.append("null");
    } else {
      sb.append(this.scores);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("feature_scores:");
    if (this.feature_scores == null) {
      sb.append("null");
    } else {
      sb.append(this.feature_scores);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("error_info:");
    if (this.error_info == null) {
      sb.append("null");
    } else {
      sb.append(this.error_info);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (res != null) {
      res.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class GBDTResponseStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public GBDTResponseStandardScheme getScheme() {
      return new GBDTResponseStandardScheme();
    }
  }

  private static class GBDTResponseStandardScheme extends org.apache.thrift.scheme.StandardScheme<GBDTResponse> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, GBDTResponse struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // RES
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.res = new com.xiaohongshu.infra.rpc.base.Result();
              struct.res.read(iprot);
              struct.setResIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // SCORES
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list36 = iprot.readListBegin();
                struct.scores = new java.util.ArrayList<RelevanceScore>(_list36.size);
                @org.apache.thrift.annotation.Nullable RelevanceScore _elem37;
                for (int _i38 = 0; _i38 < _list36.size; ++_i38)
                {
                  _elem37 = new RelevanceScore();
                  _elem37.read(iprot);
                  struct.scores.add(_elem37);
                }
                iprot.readListEnd();
              }
              struct.setScoresIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // FEATURE_SCORES
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list39 = iprot.readListBegin();
                struct.feature_scores = new java.util.ArrayList<java.lang.Double>(_list39.size);
                double _elem40;
                for (int _i41 = 0; _i41 < _list39.size; ++_i41)
                {
                  _elem40 = iprot.readDouble();
                  struct.feature_scores.add(_elem40);
                }
                iprot.readListEnd();
              }
              struct.setFeature_scoresIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // ERROR_INFO
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.error_info = iprot.readString();
              struct.setError_infoIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, GBDTResponse struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.res != null) {
        oprot.writeFieldBegin(RES_FIELD_DESC);
        struct.res.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.scores != null) {
        oprot.writeFieldBegin(SCORES_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.scores.size()));
          for (RelevanceScore _iter42 : struct.scores)
          {
            _iter42.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.feature_scores != null) {
        oprot.writeFieldBegin(FEATURE_SCORES_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.DOUBLE, struct.feature_scores.size()));
          for (double _iter43 : struct.feature_scores)
          {
            oprot.writeDouble(_iter43);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.error_info != null) {
        oprot.writeFieldBegin(ERROR_INFO_FIELD_DESC);
        oprot.writeString(struct.error_info);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class GBDTResponseTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public GBDTResponseTupleScheme getScheme() {
      return new GBDTResponseTupleScheme();
    }
  }

  private static class GBDTResponseTupleScheme extends org.apache.thrift.scheme.TupleScheme<GBDTResponse> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, GBDTResponse struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetRes()) {
        optionals.set(0);
      }
      if (struct.isSetScores()) {
        optionals.set(1);
      }
      if (struct.isSetFeature_scores()) {
        optionals.set(2);
      }
      if (struct.isSetError_info()) {
        optionals.set(3);
      }
      oprot.writeBitSet(optionals, 4);
      if (struct.isSetRes()) {
        struct.res.write(oprot);
      }
      if (struct.isSetScores()) {
        {
          oprot.writeI32(struct.scores.size());
          for (RelevanceScore _iter44 : struct.scores)
          {
            _iter44.write(oprot);
          }
        }
      }
      if (struct.isSetFeature_scores()) {
        {
          oprot.writeI32(struct.feature_scores.size());
          for (double _iter45 : struct.feature_scores)
          {
            oprot.writeDouble(_iter45);
          }
        }
      }
      if (struct.isSetError_info()) {
        oprot.writeString(struct.error_info);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, GBDTResponse struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(4);
      if (incoming.get(0)) {
        struct.res = new com.xiaohongshu.infra.rpc.base.Result();
        struct.res.read(iprot);
        struct.setResIsSet(true);
      }
      if (incoming.get(1)) {
        {
          org.apache.thrift.protocol.TList _list46 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.scores = new java.util.ArrayList<RelevanceScore>(_list46.size);
          @org.apache.thrift.annotation.Nullable RelevanceScore _elem47;
          for (int _i48 = 0; _i48 < _list46.size; ++_i48)
          {
            _elem47 = new RelevanceScore();
            _elem47.read(iprot);
            struct.scores.add(_elem47);
          }
        }
        struct.setScoresIsSet(true);
      }
      if (incoming.get(2)) {
        {
          org.apache.thrift.protocol.TList _list49 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.DOUBLE, iprot.readI32());
          struct.feature_scores = new java.util.ArrayList<java.lang.Double>(_list49.size);
          double _elem50;
          for (int _i51 = 0; _i51 < _list49.size; ++_i51)
          {
            _elem50 = iprot.readDouble();
            struct.feature_scores.add(_elem50);
          }
        }
        struct.setFeature_scoresIsSet(true);
      }
      if (incoming.get(3)) {
        struct.error_info = iprot.readString();
        struct.setError_infoIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

